[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Frank <frank.049@hotmail.com>"]

[dependencies]
nom = "3.2.1"
failure = "0.1.1"
bit-vec = "0.4.4"
rayon = "0.9"

[profile.release]
debug = true

[profile.bench]
debug = true